app:
  access_ports: tcp:5678
  default_flavor:
    name: m4.small
  deployment: kubernetes
  image_path: docker.mobiledgex.net/demoorg/images/test-github-edgebox
  image_type: 1
  key:
    name: test-github-edgebox
    organization: demoorg
    version: '1.0'
region: EU
