# App definition
region: EU
app:
  key:
    name: test-github-edgebox
    version: "1.0"
    organization: VenkyDev
  image_path: docker-stage.mobiledgex.net/venkydev/images/test-github-edgebox
  image_type: 1
  deployment: kubernetes
  default_flavor:
    name: m4.small
  access_ports: "tcp:5678"
